import './js/stars';
import './js/pagination';
import './js/search';
import './js/theme';
import './js/scroll';
import './js/signIn';
import './js/signUp';
import './js/eyeIn';
import './js/eyeUp';
import './js/modal';
import './js/country';
// import './js/fav';
import './js/header-modal';